// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clmsobcxftoimjhycnfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsbXNvYmN4ZnRvaW1qaHljbmZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNzE5NTIsImV4cCI6MjA2Mjg0Nzk1Mn0.L0t9PQ613sm28_6a3qlfbHmbiZsZRYzgft2Jq_JIvsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);